---
services:
  db:
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
    image: "mysql:5.7"
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
      - "./docker/mysql:/etc/mysql/conf.d"
  wordpress:
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_PASSWORD: wordpress
    image: "wordpress:latest"
    ports:
      - "8000:80"
    restart: always
    volumes:
      - "./build:/var/www/html/wp-content/plugins/easy-qa"
    working_dir: /var/www/html
version: "2"
volumes:
  db_data: ~
